# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c0a8d9f810b31afb7c55c95d4bb06e03a4786357d9c42869be6762546b8486bac953cbe518b7b1e90583ecb37b0fc10aee12cb0b4b61762e1cf768a2d5eba90

test:
  secret_key_base: 8daa92ff075e4fd508dd197428f2dd141131c18d0d60c2245033f2f4d5d9e2466e26b09a2267a1c5ef3f628112c620ef1334cd6c5a227105895eb32bd2343ae2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
